### ISSUE TITLE
0.7.0 fails in Gem specs

### ISSUE THREAD

**Issue by tvdeyen** [solidusio/solidus_support#54]
For instance in a Gem using the `solidus-18n` gem, trying to run the specs fails with

```
Caused by:
NameError: uninitialized constant ActiveSupport::Deprecation::DeprecatedConstantAccessor
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
/Users/tvd/.gem/ruby/2.5.8/gems/solidus_support-0.7.0/lib/solidus_support/engine_extensions.rb:5:in `<module:EngineExtensions>'
/Users/tvd/.gem/ruby/2.5.8/gems/solidus_support-0.7.0/lib/solidus_support/engine_extensions.rb:4:in `<module:SolidusSupport>'
/Users/tvd/.gem/ruby/2.5.8/gems/solidus_support-0.7.0/lib/solidus_support/engine_extensions.rb:3:in `<top (required)>'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/tvd/.gem/ruby/2.5.8/gems/solidus_support-0.7.0/lib/solidus_support.rb:5:in `<top (required)>'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/tvd/.gem/ruby/2.5.8/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/tvd/.gem/ruby/2.5.8/gems/solidus_i18n-1.3.0/lib/solidus_i18n.rb:3:in `<top (required)>'
```

**Comment by jiz4oh** [comment]
I met this same question.
And my rails version is 5.0.7.2, the ActiveSupport::Deprecation::DeprecatedConstantAccessor would be introduced from 5.1.
I think whether this gem can lock the rails version?

**Comment by Azeem838** [comment]
Hey @tvdeyen did you find a solution to this issue?
